(:*******************************************************:)
(: Test: K-DayTimeDurationMultiply-6                     :)
(: Written by: Bill Seddon                               :)
(: Date: 2007-11-22T11:31:21+01:00                       :)
(: Purpose: Simple test of multiplying -0 with xs:dayTimeDuration. :)
(:*******************************************************:)
xs:double("-0") * xs:dayTimeDuration("P3DT4H3M3S") eq xs:dayTimeDuration("PT0S")