(:*******************************************************:)
(: Test: K-DayTimeDurationMultiply-9                     :)
(: Written by: Bill Seddon                               :)
(: Date: 2007-11-22T11:31:21+01:00                       :)
(: Purpose: Simple test of multiplying a xs:dayTimeDuration with NaN. :)
(:*******************************************************:)
xs:dayTimeDuration("P3DT4H3M3S") * xs:double("NaN")